### ISSUE TITLE
How to get bitmap

### ISSUE THREAD

**Issue by LumingSun** [andreaskipf/learnedcardinalities#1]
Great work!

Is it possible to make the code about how to get the random samples and bitmap open source?

**Comment by andreaskipf** [comment]
Thanks!

The code is unfortunately part of a larger code base that we don't plan to release. However, you can easily obtain the bitmaps using your favorite DBMS (e.g., PostgreSQL) by creating a "sample table" for each base table:

1) Insert up to 1,000 uniformly selected tuples from the base table (fewer if base table doesn’t have sufficient rows) and add an id column (starting from 0).
2) Execute base table predicates on the sample table to obtain the bitmap (i.e., select the id column).

I hope this helps.

**Comment by LumingSun** [comment]
Thanks! This helps a lot!

**Comment by prekshashah5** [comment]
Could you please let me know if you were able to generate bitmaps?
